media:
  input: "assets/images"
  output: "/assets/images"

content:
  - name: kairan_items
    label: 回覧板項目
    type: collection
    path: "_kairan_items"  # ★ _kairan_items になっているか確認
    format: md  # ★ md になっているか確認
    create: true
    slug: "{{item_number}}-{{title | slug}}"
    fields:
      - {label: '項目番号', name: 'item_number', type: 'number', min: 1, default: 1}
      - {label: '目次タイトル', name: 'title', type: 'string'}
      - {label: 'ファイルID', name: 'file_id', type: 'string', required: false}
      - {label: 'ページ番号 (例: 1,3-5)', name: 'pages_str', type: 'string', required: false}
      - {label: '発行年月日', name: 'date', type: 'datetime'} # ★この行が残るようにする
      - {label: '発行回数 (月内)', name: 'issue_number', type: 'number', min: 1, default: 1}