media:
  input: "assets/images"
  output: "/assets/images"

content:
  - name: kairan_items
    label: 回覧板項目
    type: collection
    path: "_data/kairan_items"
    format: yaml  # jsonからyamlに変更
    # create: true  ← 一時的に削除して試す
    slug: "{{item_number}}-{{title | slug}}"
    fields:
      - {name: item_number, label: 項目番号, type: number, min: 1, default: 1}
      - {name: title, label: 目次タイトル, type: string}
      - {name: file_id, label: ファイルID, type: string, required: false}
      - {name: pages_str, label: ページ番号, type: string, required: false}