media:
  input: "assets/images"
  output: "/assets/images"

content:
  - name: kairan_items
    label: 回覧板項目
    type: collection
    path: "_kairan_items"  # ★ _kairan_items に戻します
    format: md # ★ md を明示的に指定します
    create: true
    slug: "{{item_number}}-{{title | slug}}"
    fields:
      - {name: item_number, label: 項目番号, type: number, min: 1, default: 1}
      - {name: title, label: 目次タイトル, type: string}
      - {name: file_id, label: ファイルID, type: string, required: false}
      - {name: pages_str, label: ページ番号, type: string, required: false}