backend:
  # GitHub Pagesでホストされているため、認証バックエンドとしてGitHubを使用します
  name: github
  # あなたのGitHubアカウント名とリポジトリ名を指定してください
  repo: yazirobe227/kanou-jichikai-kairan
  # ブランチを指定します（通常はmain）
  branch: main

# メディア（画像など）の保存場所と公開URLを設定します
media_folder: "images/uploads"
public_folder: "/images/uploads"

# 最小限のコレクションを定義します (CMSログイン後のテスト用)
collections:
  - name: "posts"
    label: "テスト投稿"
    folder: "_posts" # Jekyllのデフォルトのブログ投稿フォルダ
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "レイアウト", name: "layout", widget: "hidden", default: "post"}
      - {label: "タイトル", name: "title", widget: "string", required: true}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "本文", name: "body", widget: "markdown"}